server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/potatalk
    username: root
    password: 1234
  rabbitmq:
    host: 127.0.0.1
    port: 5672
logging:
  level:
    org.springframework.r2dbc.core: debug