global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: "chat-service"
    metrics_path: "/actuator/prometheus"
    scheme: http
    static_configs:
      - targets: ["host.docker.internal:8082"]
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['host.docker.internal:9308']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: [ 'host.docker.internal:15692' ]