server:
  port: 8082

spring:
  data:
    mongodb:
      database: potatalk
      uri: mongodb://localhost:27017
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    org.springframework.r2dbc.core: debug